"""init 7 casestate table groups

Revision ID: 92bd99c6379c
Revises: 
Create Date: 2026-07-17 19:05:04.606060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92bd99c6379c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('requested_facility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('conflicts',
    sa.Column('conflict_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('issue_key', sa.String(), nullable=False),
    sa.Column('source_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('targeted_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    op.create_index(op.f('ix_conflicts_case_id'), 'conflicts', ['case_id'], unique=False)
    op.create_table('decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('requested_amount_vnd', sa.Float(), nullable=True),
    sa.Column('recommended_amount_vnd', sa.Float(), nullable=True),
    sa.Column('recommended_tenor_months', sa.Integer(), nullable=True),
    sa.Column('hard_gates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions_precedent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dissent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('decision_matrix_version', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_decisions_case_id'), 'decisions', ['case_id'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('minio_key', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('case_id', 'seq', name='uq_event_case_seq')
    )
    op.create_index(op.f('ix_events_case_id'), 'events', ['case_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finding_key', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('issue_key', sa.String(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('stance', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_key', 'version', name='uq_finding_key_version')
    )
    op.create_index(op.f('ix_findings_case_id'), 'findings', ['case_id'], unique=False)
    op.create_index(op.f('ix_findings_finding_key'), 'findings', ['finding_key'], unique=False)
    op.create_index(op.f('ix_findings_issue_key'), 'findings', ['issue_key'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('dependency', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('extracted_fields',
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('field_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_fields')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_findings_issue_key'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_key'), table_name='findings')
    op.drop_index(op.f('ix_findings_case_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_events_case_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('documents')
    op.drop_index(op.f('ix_decisions_case_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_conflicts_case_id'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_table('cases')
    # ### end Alembic commands ###
